In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import pandas as pd
import numpy as np

In [4]:
data= pd.read_excel('/content/drive/MyDrive/Tanjila_mam/DS-Healthcare_version_2.xlsx')

In [5]:
target = 'Type'

In [6]:
X= data.loc[:,data.columns != target]
y = data[target]

In [7]:
y.value_counts()

ischemic      581219
healthy       267360
arrhythmic     40238
Name: Type, dtype: int64

In [8]:
def fun_split(X,Y,test_size,feature):

    f=Y.value_counts()
    rows=X.shape[0]
    talika=[]
    count=0
    for i in f:
        talika.append(i)
    train_size=1-test_size
    start=0

    switch=False

    for i in talika :

        train=start+int(i*train_size)
        f= X[feature][train]
        count1=0
        count2=0
        index1=train
        index2=train+1
        end=start+i-1
        
        while X[feature][index1]==f:
            if index1<start:
                break
            index1-=1
            count1+=1
            
            
        while X[feature][index2]==f:
            if index2>end:
                break
            index2+=1
            count2+=1

        if count1>=count2:
            train+=count2
        else:
            train-=count1
        
        
        if switch == False:
            X_train= X[start:train+1]
            X_test= X[train+1:end]
            Y_train = Y[start:train+1]
            Y_test = Y[train+1:end]
            switch=True

        else:
            X_train=pd.concat([X_train, X[start:train+1]], ignore_index=True)
            X_test=pd.concat([X_test, X[train+1:end+1]], ignore_index=True)
            Y_train=pd.concat([Y_train, Y[start:train+1]], ignore_index=True)
            Y_test=pd.concat([Y_test, Y[train+1:end+1]], ignore_index=True)

        start=start+i

    print('Train Percentage:',X_train.shape[0]/rows)

    return X_train,X_test,Y_train,Y_test

In [9]:
 X_train, X_test, y_train, y_test = fun_split(X,y, test_size=0.2, feature= 'Subject')

Train Percentage: 0.8002839729663137


In [10]:
"""#testing if there is any mixing with training subject and testing subject
from tqdm.notebook import tqdm
train = list(X_train["Subject"])
test = list(X_test["Subject"])

dup = []

for i in tqdm(test):
  if i in train:
    dup.append(i)
print(dup)"""

  0%|          | 0/177510 [00:00<?, ?it/s]

[]


In [11]:
X_train= X_train.loc[:,X_train.columns != 'Subject']
X_train= X_train.loc[:,X_train.columns != 'Time']
X_train= X_train.loc[:,X_train.columns != 'Cycle']

X_test= X_test.loc[:,X_test.columns != 'Subject']
X_test= X_test.loc[:,X_test.columns != 'Time']
X_test= X_test.loc[:,X_test.columns != 'Cycle']

In [12]:
y_test.value_counts()

ischemic      116816
healthy        53135
arrhythmic      7559
Name: Type, dtype: int64

In [13]:
y_train.value_counts()

ischemic      464402
healthy       214225
arrhythmic     32679
Name: Type, dtype: int64

In [14]:
X_train.head(-1)

RR-I         HR    R-H    P-H       QRS       PRQ        QT  \
0       0.932000  64.377682  3.305  3.810  0.088000  0.160000  0.384000   
1       1.004000  59.760956  3.285  3.810  0.100000  0.160000  0.640000   
2       0.996000  60.240964  3.340  3.830  0.128000  0.148000  0.628000   
3       1.016000  59.055118  3.325  3.810  0.108000  0.172000  0.388000   
4       0.972000  61.728395  3.290  3.765  0.100000  0.160000  0.372000   
...          ...        ...    ...    ...       ...       ...       ...   
711300  0.716667  83.720930  0.725 -0.765  0.111111  0.161111  0.472222   
711301  0.694444  86.400000  0.725 -0.795  0.105556  0.161111  0.452778   
711302  0.722222  83.076923  0.685 -0.780  0.094444  0.155556  0.477778   
711303  0.713889  84.046693  0.760 -0.730  0.111111  0.161111  0.480556   
711304  0.711111  84.375000  0.735 -0.725  0.105556  0.161111  0.458333   

             QTC        ST  
0       0.397762  0.296000  
1       0.638724  0.540000  
2       0.629260  0.500000  
3       0.384933  0.280000  
4       0.377320  0.272000  
...          ...       ...  
711300  0.557812  0.372222  
711301  0.543333  0.355556  
711302  0.562200  0.383333  
711303  0.568759  0.372222  
711304  0.543516  0.361111  

[711305 rows x 9 columns]

In [15]:
X_test.head(-1)

RR-I         HR    R-H    P-H       QRS       PRQ        QT  \
0       0.856000  70.093458  2.275 -0.435  0.140000  0.132000  0.412000   
1       0.796000  75.376884  1.905 -0.590  0.132000  0.128000  0.380000   
2       0.916000  65.502183  1.860 -0.425  0.132000  0.128000  0.392000   
3       1.388000  43.227666  0.955 -0.480  0.144000  0.132000  0.400000   
4       0.680000  88.235294  2.200 -0.435  0.136000  0.128000  0.372000   
...          ...        ...    ...    ...       ...       ...       ...   
177504  0.638889  93.913043  0.680 -0.315  0.063889  0.158333  0.402778   
177505  0.652778  91.914894  0.660 -0.335  0.066667  0.163889  0.411111   
177506  0.675000  88.888889  0.605 -0.345  0.066667  0.172222  0.413889   
177507  0.647222  92.703863  0.795 -0.335  0.055556  0.161111  0.397222   
177508  0.647222  92.703863  0.825 -0.330  0.069444  0.152778  0.400000   

             QTC        ST  
0       0.445308  0.292000  
1       0.425919  0.272000  
2       0.409580  0.284000  
3       0.339520  0.304000  
4       0.451116  0.260000  
...          ...       ...  
177504  0.503910  0.350000  
177505  0.508834  0.355556  
177506  0.503770  0.358333  
177507  0.493750  0.341667  
177508  0.497202  0.344444  

[177509 rows x 9 columns]

In [16]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier ()

rf.fit(X_train,y_train)

y_pred = rf.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[  1596    261   5702]
 [ 14690   9903  28542]
 [   719      5 116092]]
              precision    recall  f1-score   support

  arrhythmic       0.09      0.21      0.13      7559
     healthy       0.97      0.19      0.31     53135
    ischemic       0.77      0.99      0.87    116816

    accuracy                           0.72    177510
   macro avg       0.61      0.46      0.44    177510
weighted avg       0.80      0.72      0.67    177510

Accurecy:  0.7187820404484254


In [18]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier()

ada.fit(X_train, y_train)

y_pred = ada.predict(X_test)

In [19]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[  2223    763   4573]
 [  3862  31914  17359]
 [   620     13 116183]]
              precision    recall  f1-score   support

  arrhythmic       0.33      0.29      0.31      7559
     healthy       0.98      0.60      0.74     53135
    ischemic       0.84      0.99      0.91    116816

    accuracy                           0.85    177510
   macro avg       0.72      0.63      0.66    177510
weighted avg       0.86      0.85      0.84    177510

Accurecy:  0.8468255309560024


In [20]:
from sklearn.ensemble import GradientBoostingClassifier

GBC = GradientBoostingClassifier()
GBC.fit(X_train, y_train)

y_pred = GBC.predict(X_test)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[  3244    605   3710]
 [  4212  30356  18567]
 [  1366     15 115435]]
              precision    recall  f1-score   support

  arrhythmic       0.37      0.43      0.40      7559
     healthy       0.98      0.57      0.72     53135
    ischemic       0.84      0.99      0.91    116816

    accuracy                           0.84    177510
   macro avg       0.73      0.66      0.67    177510
weighted avg       0.86      0.84      0.83    177510

Accurecy:  0.8395865021688919


In [27]:
!pip install xgboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [28]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [29]:

import xgboost as xgb
xgb_default = xgb.XGBClassifier()
xgb_default.fit(X_train,y_train)
y_pred = xgb_default.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[  5975    117   1467]
 [  5598  21215  26322]
 [   309     13 116494]]
              precision    recall  f1-score   support

           0       0.50      0.79      0.61      7559
           1       0.99      0.40      0.57     53135
           2       0.81      1.00      0.89    116816

    accuracy                           0.81    177510
   macro avg       0.77      0.73      0.69    177510
weighted avg       0.85      0.81      0.78    177510

Accurecy:  0.8094417215931496
