In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np

In [ ]:
data= pd.read_excel('/content/drive/MyDrive/Tanjila_mam/DS-Healthcare.xlsx')

In [ ]:
target = 'Type'

In [ ]:
X= data.loc[:,data.columns != target]
y = data[target]

In [ ]:
y.value_counts()

ischemic      581219
healthy       267360
arrhythmic     40238
Name: Type, dtype: int64

In [ ]:
def fun_split(X,Y,test_size,feature):

    f=Y.value_counts()
    rows=X.shape[0]
    initial_list=[]
    count=0
    for i in f:
        initial_list.append(i)
    train_size=1-test_size
    start=0

    switch=False

    for i in initial_list:

        train=start+int(i*train_size)
        f= X[feature][train]
        count1=0
        count2=0
        index1=train
        index2=train+1
        end=start+i-1
        
        while X[feature][index1]==f:
            if index1<start:
                break
            index1-=1
            count1+=1
            
            
        while X[feature][index2]==f:
            if index2>end:
                break
            index2+=1
            count2+=1

        if count1>=count2:
            train+=count2
        else:
            train-=count1
        
        
        if switch == False:
            X_train= X[start:train+1]
            X_test= X[train+1:end]
            Y_train = Y[start:train+1]
            Y_test = Y[train+1:end]
            switch=True

        else:
            X_train=pd.concat([X_train, X[start:train+1]], ignore_index=True)
            X_test=pd.concat([X_test, X[train+1:end+1]], ignore_index=True)
            Y_train=pd.concat([Y_train, Y[start:train+1]], ignore_index=True)
            Y_test=pd.concat([Y_test, Y[train+1:end+1]], ignore_index=True)

        start=start+i

    print('Train Percentage:',X_train.shape[0]/rows)

    return X_train,X_test,Y_train,Y_test

In [ ]:
 X_train, X_test, y_train, y_test = fun_split(X,y, test_size=0.2, feature= 'Subject')

Train Percentage: 0.8002839729663137


In [ ]:
"""#testing if there is any mixing with training subject and testing subject
from tqdm.notebook import tqdm
train = list(X_train["Subject"])
test = list(X_test["Subject"])

dup = []

for i in tqdm(test):
  if i in train:
    dup.append(i)
print(dup)"""

'#testing if there is any mixing with training subject and testing subject\nfrom tqdm.notebook import tqdm\ntrain = list(X_train["Subject"])\ntest = list(X_test["Subject"])\n\ndup = []\n\nfor i in tqdm(test):\n  if i in train:\n    dup.append(i)\nprint(dup)'

In [ ]:
X_train= X_train.loc[:,X_train.columns != 'Subject']
X_train= X_train.loc[:,X_train.columns != 'Time']
X_train= X_train.loc[:,X_train.columns != 'Cycle']

X_test= X_test.loc[:,X_test.columns != 'Subject']
X_test= X_test.loc[:,X_test.columns != 'Time']
X_test= X_test.loc[:,X_test.columns != 'Cycle']

In [ ]:
y_train.value_counts()

ischemic      464402
healthy       214225
arrhythmic     32679
Name: Type, dtype: int64

In [ ]:
!pip install imbalanced-learn
from imblearn.over_sampling import SMOTE

smote = SMOTE()

X_train, y_train= smote.fit_resample(X_train, y_train)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
y_train.value_counts()

ischemic      464402
healthy       464402
arrhythmic    464402
Name: Type, dtype: int64

In [ ]:
X_train.head(-1)

RR-I         HR        R-H       P-H       QRS       PRQ        QT  \
0        0.932  64.377682   3.305000  3.810000  0.088000  0.160000  0.384000   
1        1.004  59.760956   3.285000  3.810000  0.100000  0.160000  0.640000   
2        0.996  60.240964   3.340000  3.830000  0.128000  0.148000  0.628000   
3        1.016  59.055118   3.325000  3.810000  0.108000  0.172000  0.388000   
4        0.972  61.728395   3.290000  3.765000  0.100000  0.160000  0.372000   
...        ...        ...        ...       ...       ...       ...       ...   
1393200  1.044  57.471260   0.546880  0.016341  0.084000  0.134772  0.458772   
1393201  1.140  52.631580  10.105774  8.086968  0.088451  0.199097  0.412161   
1393202  0.900  66.666670   0.683092 -0.031241  0.095796  0.135796  0.407796   
1393203  0.996  60.240960   0.765248  0.091418  0.096000  0.164431  0.444461   
1393204  0.768  78.125000  10.385056  8.036416  0.081472  0.144000  0.392639   

              QTC        ST  
0        0.397762  0.296000  
1        0.638724  0.540000  
2        0.629260  0.500000  
3        0.384933  0.280000  
4        0.377320  0.272000  
...           ...       ...  
1393200  0.449000  0.398772  
1393201  0.386023  0.346677  
1393202  0.429855  0.347796  
1393203  0.445350  0.376461  
1393204  0.448038  0.330111  

[1393205 rows x 9 columns]

In [ ]:
X_test.head(-1)

RR-I         HR    R-H    P-H       QRS       PRQ        QT  \
0       0.856000  70.093458  2.275 -0.435  0.140000  0.132000  0.412000   
1       0.796000  75.376884  1.905 -0.590  0.132000  0.128000  0.380000   
2       0.916000  65.502183  1.860 -0.425  0.132000  0.128000  0.392000   
3       1.388000  43.227666  0.955 -0.480  0.144000  0.132000  0.400000   
4       0.680000  88.235294  2.200 -0.435  0.136000  0.128000  0.372000   
...          ...        ...    ...    ...       ...       ...       ...   
177504  0.638889  93.913043  0.680 -0.315  0.063889  0.158333  0.402778   
177505  0.652778  91.914894  0.660 -0.335  0.066667  0.163889  0.411111   
177506  0.675000  88.888889  0.605 -0.345  0.066667  0.172222  0.413889   
177507  0.647222  92.703863  0.795 -0.335  0.055556  0.161111  0.397222   
177508  0.647222  92.703863  0.825 -0.330  0.069444  0.152778  0.400000   

             QTC        ST  
0       0.445308  0.292000  
1       0.425919  0.272000  
2       0.409580  0.284000  
3       0.339520  0.304000  
4       0.451116  0.260000  
...          ...       ...  
177504  0.503910  0.350000  
177505  0.508834  0.355556  
177506  0.503770  0.358333  
177507  0.493750  0.341667  
177508  0.497202  0.344444  

[177509 rows x 9 columns]

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier ()

rf.fit(X_train,y_train)

y_pred = rf.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[  3803    424   3332]
 [ 16615   9891  26629]
 [  2370      6 114440]]
              precision    recall  f1-score   support

  arrhythmic       0.17      0.50      0.25      7559
     healthy       0.96      0.19      0.31     53135
    ischemic       0.79      0.98      0.88    116816

    accuracy                           0.72    177510
   macro avg       0.64      0.56      0.48    177510
weighted avg       0.82      0.72      0.68    177510

Accurecy:  0.7218410230409554


In [ ]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier()

ada.fit(X_train, y_train)

y_pred = ada.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[  4921    683   1955]
 [ 19207  27952   5976]
 [  4318     12 112486]]
              precision    recall  f1-score   support

  arrhythmic       0.17      0.65      0.27      7559
     healthy       0.98      0.53      0.68     53135
    ischemic       0.93      0.96      0.95    116816

    accuracy                           0.82    177510
   macro avg       0.69      0.71      0.64    177510
weighted avg       0.91      0.82      0.84    177510

Accurecy:  0.8188778097008619


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

GBC = GradientBoostingClassifier()
GBC.fit(X_train, y_train)

y_pred = GBC.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[  5147    717   1695]
 [ 11930  33841   7364]
 [  4217     10 112589]]
              precision    recall  f1-score   support

  arrhythmic       0.24      0.68      0.36      7559
     healthy       0.98      0.64      0.77     53135
    ischemic       0.93      0.96      0.94    116816

    accuracy                           0.85    177510
   macro avg       0.72      0.76      0.69    177510
weighted avg       0.91      0.85      0.87    177510

Accurecy:  0.8539068221508648


In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [ ]:

import xgboost as xgb
xgb_default = xgb.XGBClassifier()
xgb_default.fit(X_train,y_train)
y_pred = xgb_default.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[  6410    574    575]
 [  9252  16746  27137]
 [   325     18 116473]]
              precision    recall  f1-score   support

           0       0.40      0.85      0.54      7559
           1       0.97      0.32      0.48     53135
           2       0.81      1.00      0.89    116816

    accuracy                           0.79    177510
   macro avg       0.72      0.72      0.64    177510
weighted avg       0.84      0.79      0.75    177510

Accurecy:  0.7865979381443299
