In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#<font color = 'DAF7A6'>Functions Thats Really Needed 

In [2]:
!pip install imbalanced-learn

from imblearn.over_sampling import SMOTE

def balance(X_temp, y_temp):
  smote = SMOTE()
  X_temp, y_temp= smote.fit_resample(X_temp, y_temp)

  return pd.concat([pd.DataFrame(X_temp), pd.DataFrame(y_temp)], axis=1)


from joblib import Parallel, delayed
from google.colab import files
import joblib
  

def save_model(model,model_name):
 joblib.dump(model, model_name)
  
def load_model(model_name):
  return joblib.load(model_name)



def Search_Null(dataset):
  dic={}
  for col in list(dataset.columns):
    rows = []
    flage = 0
    for row in range(dataset.shape[0]):
      if str(dataset[col][row]) == "nan":
        rows.append(row)
        flage = 1
    if flage ==1:
      dic[col] = rows
  
  return dic




def divide_dataset(dataset,percentage,random_state = 0):

  rows,cols = dataset.shape

  if random_state == 0:
    return dataset.iloc[:int(rows*(percentage)),:]
  else:
    import random
    l_r = random.sample(range(0, rows), int(rows*(percentage)))
    return dataset.iloc[l_r,:]


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np
import pandas as pd
from tqdm import tqdm

dataset=pd.read_excel("/content/drive/MyDrive/Iqram Sir/Refactored_Dataset.xlsx")



In [4]:

target="Sleep Stage"

classes = list(set(dataset[target]))

In [5]:
dataset.head()

Sleep Stage  MeanP_Alpha_F4  MedianF_Alpha_F4  MeanF_Alpha_F4  \
0           W         0.00051           8.74146        18.48195   
1           W         0.00040          10.24000        17.48293   
2           W         0.00036           9.74049        17.98244   
3           W         0.00035          10.11512        17.60780   
4           W         0.00033           9.74049        17.60780   

   Spectral Edge_Alpha_F4  PeakF_Alpha_F4  MeanP_Beta_F4  MedianF_Beta_F4  \
0                17.48293         8.24195        0.00071         19.73073   
1                16.85854        10.61463        0.00051         17.23317   
2                17.48293         8.74146        0.00047         17.60780   
3                17.10829         9.61561        0.00047         17.35805   
4                17.23317         8.11707        0.00043         17.23317   

   MeanF_Beta_F4  Spectral Edge_Beta_F4  ...      DAR_G     DTR_F4    DTR_C4  \
0       29.84585               33.84195  ...  18.191758   8.851240  5.786885   
1       26.34927               29.34634  ...  16.621053   8.693548  5.173913   
2       25.47512               28.22244  ...  15.327441  16.389831  7.090909   
3       26.47415               28.72195  ...   4.718095   5.302326  3.600000   
4       25.84976               28.09756  ...   8.542423   8.226415  3.921053   

      DTR_O2      DTR_G   DTABR_F4  DTABR_C4   DTABR_O2   DTABR_G       P_G  
0  18.564103  11.067409   9.770492  3.833333   8.670455  7.424760  0.009177  
1  28.920000  14.262487   6.604396  3.155556  12.262295  7.340749  0.006355  
2   9.583333  11.021358  12.361446  4.188235   4.618182  7.055954  0.006283  
3   3.640000   4.180775   3.304878  2.067416   1.901639  2.424644  0.002777  
4   7.291667   6.479711   6.434211  2.527027   3.491228  4.150822  0.003691  

[5 rows x 112 columns]

In [ ]:
Search_Null(dataset)

{}

In [ ]:
dataset.shape

(108450, 112)

In [ ]:
#new_dataset = divide_dataset(dataset,0.1,1)

In [ ]:
set(list(dataset[target]))

{'N1', 'N2', 'N3', 'R', 'W'}

In [6]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
dataset[target]=encoder.fit_transform(dataset[target])

In [ ]:
set(list(dataset[target])) # alphabet wise

{0, 1, 2, 3, 4}

In [8]:
#X = new_dataset.loc[:, new_dataset.columns!=target]
#y = new_dataset[target]
#X = dataset[list_of_feat]
X = dataset.loc[:, dataset.columns!=target]
y = dataset[target]

In [15]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

#apply SelectKBest class to extract top 10 best features
bestfeatures = SelectKBest(score_func=chi2, k=10)
fit = bestfeatures.fit(X,y)

dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)


#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
     
featureScores.nlargest(50,'Score').to_csv("Univarient.csv")


feat = pd.read_csv("/content/Univarient.csv")
list_of_feat = list(feat.loc[:,"Specs"])

In [16]:
len(list_of_feat)

50

In [18]:
X = dataset[list_of_feat]
y = dataset[target]

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)


In [21]:
new_dataset_2=balance(X_train,y_train)

X_train = new_dataset_2.loc[:, new_dataset_2.columns!=target]
y_train = new_dataset_2[target]

In [22]:
new_dataset_2.shape

(157790, 51)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from tqdm import tqdm
N=1000
k_range = range (51,N+1,10)
scores={}
scores_list = []
for k in tqdm(k_range):
  classifier = RandomForestClassifier(n_estimators=k,random_state=0)
  classifier.fit(X_train, y_train)
  y_pred=classifier.predict(X_test)
  scores[k] = accuracy_score(y_test,y_pred)
  scores_list.append(accuracy_score(y_test,y_pred))
  print(str(k)+"/"+str(N)+" round completed......................... Accurecy: "+str(accuracy_score(y_test,y_pred)))



%matplotlib inline
import matplotlib.pyplot as plt

plt.figure(figsize = (25,10))
plt.plot(k_range,scores_list)
plt.xlabel('Value of n_estimators')
plt.ylabel ('Testing Accuracy')



print("The best n_estimators:")
best_estimator=list(scores.keys())[scores_list.index(max(scores_list))]
print(best_estimator)

  1%|          | 1/100 [00:01<02:26,  1.48s/it]

1/1000 round completed......................... Accurecy: 0.5843706777316736


  2%|▏         | 2/100 [00:17<16:09,  9.89s/it]

11/1000 round completed......................... Accurecy: 0.7082065467957585


  3%|▎         | 3/100 [00:47<30:51, 19.09s/it]

21/1000 round completed......................... Accurecy: 0.7281235592438912


  4%|▍         | 4/100 [01:31<46:33, 29.10s/it]

31/1000 round completed......................... Accurecy: 0.7360073766712771


  5%|▌         | 5/100 [02:30<1:03:00, 39.79s/it]

41/1000 round completed......................... Accurecy: 0.7395112955278931


  6%|▌         | 6/100 [03:43<1:20:03, 51.10s/it]

51/1000 round completed......................... Accurecy: 0.7404794836330106


  7%|▋         | 7/100 [05:11<1:37:54, 63.16s/it]

61/1000 round completed......................... Accurecy: 0.7425080682342093


  8%|▊         | 8/100 [06:53<1:55:45, 75.50s/it]

71/1000 round completed......................... Accurecy: 0.7451821115721531


  9%|▉         | 9/100 [08:50<2:14:06, 88.42s/it]

81/1000 round completed......................... Accurecy: 0.7461964038727524


 10%|█         | 10/100 [11:02<2:32:48, 101.87s/it]

91/1000 round completed......................... Accurecy: 0.7461964038727524


 11%|█         | 11/100 [13:29<2:51:29, 115.61s/it]

101/1000 round completed......................... Accurecy: 0.7466574458275703


 12%|█▏        | 12/100 [16:09<3:09:24, 129.14s/it]

111/1000 round completed......................... Accurecy: 0.7480866758875058


 13%|█▎        | 13/100 [19:03<3:26:58, 142.74s/it]

121/1000 round completed......................... Accurecy: 0.7481327800829876


 14%|█▍        | 14/100 [22:10<3:43:54, 156.21s/it]

131/1000 round completed......................... Accurecy: 0.748686030428769


 15%|█▌        | 15/100 [25:36<4:02:25, 171.12s/it]

141/1000 round completed......................... Accurecy: 0.7478561549100968


 16%|█▌        | 16/100 [29:12<4:18:35, 184.71s/it]

151/1000 round completed......................... Accurecy: 0.748040571692024


 17%|█▋        | 17/100 [33:00<4:33:24, 197.65s/it]

161/1000 round completed......................... Accurecy: 0.748040571692024


 18%|█▊        | 18/100 [37:01<4:48:07, 210.82s/it]

171/1000 round completed......................... Accurecy: 0.7484094052558783


 19%|█▉        | 19/100 [41:17<5:02:43, 224.25s/it]

181/1000 round completed......................... Accurecy: 0.7475795297372061


 20%|██        | 20/100 [45:49<5:18:08, 238.60s/it]

191/1000 round completed......................... Accurecy: 0.7473951129552789


 21%|██        | 21/100 [50:35<5:33:07, 253.01s/it]

201/1000 round completed......................... Accurecy: 0.7477639465191332


 22%|██▏       | 22/100 [55:35<5:47:02, 266.95s/it]

211/1000 round completed......................... Accurecy: 0.7472106961733518


 23%|██▎       | 23/100 [1:00:49<6:00:44, 281.09s/it]

221/1000 round completed......................... Accurecy: 0.7473029045643154


 24%|██▍       | 24/100 [1:06:18<6:14:18, 295.51s/it]

231/1000 round completed......................... Accurecy: 0.7474412171507607


 25%|██▌       | 25/100 [1:12:02<6:27:22, 309.90s/it]

241/1000 round completed......................... Accurecy: 0.7477639465191332


 26%|██▌       | 26/100 [1:17:59<6:39:48, 324.17s/it]

251/1000 round completed......................... Accurecy: 0.7474873213462425


 27%|██▋       | 27/100 [1:24:17<6:54:10, 340.42s/it]

261/1000 round completed......................... Accurecy: 0.7484555094513601


 28%|██▊       | 28/100 [1:31:00<7:10:57, 359.13s/it]

271/1000 round completed......................... Accurecy: 0.7482710926694329


 29%|██▉       | 29/100 [1:37:44<7:20:58, 372.66s/it]

281/1000 round completed......................... Accurecy: 0.7479483633010604


 30%|███       | 30/100 [1:44:45<7:31:24, 386.93s/it]

291/1000 round completed......................... Accurecy: 0.7467957584140157


 31%|███       | 31/100 [1:51:58<7:41:03, 400.92s/it]

301/1000 round completed......................... Accurecy: 0.7476717381281697


 32%|███▏      | 32/100 [1:59:29<7:51:23, 415.93s/it]

311/1000 round completed......................... Accurecy: 0.7474873213462425


 33%|███▎      | 33/100 [2:07:10<7:59:30, 429.42s/it]

321/1000 round completed......................... Accurecy: 0.7483171968649147


 34%|███▍      | 34/100 [2:15:11<8:09:25, 444.93s/it]

331/1000 round completed......................... Accurecy: 0.7483633010603965


 35%|███▌      | 35/100 [2:23:43<8:23:49, 465.06s/it]

341/1000 round completed......................... Accurecy: 0.748686030428769


 36%|███▌      | 36/100 [2:32:13<8:30:18, 478.41s/it]

351/1000 round completed......................... Accurecy: 0.7485016136468419


 37%|███▋      | 37/100 [2:40:51<8:34:48, 490.29s/it]

361/1000 round completed......................... Accurecy: 0.7490087597971415


 38%|███▊      | 38/100 [2:49:45<8:40:21, 503.57s/it]

371/1000 round completed......................... Accurecy: 0.7491931765790687


 39%|███▉      | 39/100 [2:58:56<8:46:26, 517.81s/it]

381/1000 round completed......................... Accurecy: 0.7486399262332872


 40%|████      | 40/100 [3:08:19<8:51:25, 531.43s/it]

391/1000 round completed......................... Accurecy: 0.7485016136468419


 41%|████      | 41/100 [3:17:54<8:55:17, 544.36s/it]

401/1000 round completed......................... Accurecy: 0.7477178423236515


 42%|████▏     | 42/100 [3:27:43<8:59:17, 557.88s/it]

411/1000 round completed......................... Accurecy: 0.7480866758875058


 43%|████▎     | 43/100 [3:37:53<9:04:37, 573.29s/it]

421/1000 round completed......................... Accurecy: 0.7476717381281697


 44%|████▍     | 44/100 [3:48:25<9:11:31, 590.92s/it]

431/1000 round completed......................... Accurecy: 0.747810050714615


 45%|████▌     | 45/100 [3:59:04<9:15:01, 605.48s/it]

441/1000 round completed......................... Accurecy: 0.7473029045643154


 46%|████▌     | 46/100 [4:09:52<9:16:29, 618.32s/it]

451/1000 round completed......................... Accurecy: 0.7474412171507607


 47%|████▋     | 47/100 [4:20:58<9:18:47, 632.60s/it]

461/1000 round completed......................... Accurecy: 0.7477178423236515


 48%|████▊     | 48/100 [4:32:20<9:20:59, 647.30s/it]

471/1000 round completed......................... Accurecy: 0.7473490087597972


 49%|████▉     | 49/100 [4:44:03<9:24:26, 664.04s/it]

481/1000 round completed......................... Accurecy: 0.7474412171507607


 50%|█████     | 50/100 [4:56:24<9:32:32, 687.05s/it]

491/1000 round completed......................... Accurecy: 0.7474873213462425


 51%|█████     | 51/100 [5:08:59<9:37:52, 707.60s/it]

501/1000 round completed......................... Accurecy: 0.7468418626094975


 52%|█████▏    | 52/100 [5:21:33<9:37:07, 721.40s/it]

511/1000 round completed......................... Accurecy: 0.7470262793914246


 53%|█████▎    | 53/100 [5:34:20<9:35:55, 735.23s/it]

521/1000 round completed......................... Accurecy: 0.746519133241125


 54%|█████▍    | 54/100 [5:47:20<9:33:52, 748.53s/it]

531/1000 round completed......................... Accurecy: 0.7473029045643154


 55%|█████▌    | 55/100 [6:00:37<9:32:19, 763.10s/it]

541/1000 round completed......................... Accurecy: 0.7473951129552789


 56%|█████▌    | 56/100 [6:14:08<9:30:06, 777.43s/it]

551/1000 round completed......................... Accurecy: 0.74716459197787


 57%|█████▋    | 57/100 [6:27:51<9:26:51, 790.97s/it]

561/1000 round completed......................... Accurecy: 0.7469801751959428


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from tqdm import tqdm
N=10000
k_range = range (1,N+1)
scores={}
scores_list = []
for k in tqdm(k_range):
  classifier = RandomForestClassifier(max_depth=k,random_state=0)
  classifier.fit(X_train, y_train)
  y_pred=classifier.predict(X_test)
  scores[k] = accuracy_score(y_test,y_pred)
  scores_list.append(accuracy_score(y_test,y_pred))
  print(str(k)+"/"+str(N)+" round completed......................... Accurecy: "+str(accuracy_score(y_test,y_pred)))



%matplotlib inline
import matplotlib.pyplot as plt

plt.figure(figsize = (25,10))
plt.plot(k_range,scores_list)
plt.xlabel('Value of n_estimators')
plt.ylabel ('Testing Accuracy')



print("The best Depth:")
best_depth=list(scores.keys())[scores_list.index(max(scores_list))]
print(best_depth)

  0%|          | 1/10000 [00:21<60:37:00, 21.82s/it]

1/10000 round completed......................... Accurecy: 0.43992623328722913


  0%|          | 2/10000 [00:51<72:48:01, 26.21s/it]

2/10000 round completed......................... Accurecy: 0.5236514522821577


  0%|          | 3/10000 [01:33<92:49:37, 33.43s/it]

3/10000 round completed......................... Accurecy: 0.5588289534347626


  0%|          | 4/10000 [02:26<115:05:12, 41.45s/it]

4/10000 round completed......................... Accurecy: 0.5830797602581835


  0%|          | 5/10000 [03:32<138:59:03, 50.06s/it]

5/10000 round completed......................... Accurecy: 0.6053019824804057


  0%|          | 6/10000 [04:49<164:18:01, 59.18s/it]

6/10000 round completed......................... Accurecy: 0.6289534347625634


  0%|          | 7/10000 [06:16<189:55:02, 68.42s/it]

7/10000 round completed......................... Accurecy: 0.6442600276625173


  0%|          | 8/10000 [07:53<215:19:57, 77.58s/it]

8/10000 round completed......................... Accurecy: 0.6612724757952974


  0%|          | 9/10000 [09:42<242:40:57, 87.44s/it]

9/10000 round completed......................... Accurecy: 0.6810511756569848


  0%|          | 10/10000 [11:41<269:02:48, 96.95s/it]

10/10000 round completed......................... Accurecy: 0.6977408944213923


  0%|          | 11/10000 [13:49<295:58:36, 106.67s/it]

11/10000 round completed......................... Accurecy: 0.7126325495620102


  0%|          | 12/10000 [16:10<324:21:24, 116.91s/it]

12/10000 round completed......................... Accurecy: 0.7239280774550484


  0%|          | 13/10000 [18:39<351:20:40, 126.65s/it]

13/10000 round completed......................... Accurecy: 0.7362840018441679


  0%|          | 14/10000 [21:17<378:10:48, 136.34s/it]

14/10000 round completed......................... Accurecy: 0.7417242969110189


  0%|          | 15/10000 [24:03<402:14:57, 145.03s/it]

15/10000 round completed......................... Accurecy: 0.7501613646841863


  0%|          | 16/10000 [26:56<425:37:06, 153.47s/it]

16/10000 round completed......................... Accurecy: 0.7539419087136929


  0%|          | 17/10000 [29:54<446:25:00, 160.98s/it]

17/10000 round completed......................... Accurecy: 0.7603964960811433


  0%|          | 18/10000 [32:58<465:46:58, 167.98s/it]

18/10000 round completed......................... Accurecy: 0.7640848317196864


  0%|          | 19/10000 [36:05<481:19:00, 173.60s/it]

19/10000 round completed......................... Accurecy: 0.7660673121254035


  0%|          | 20/10000 [39:15<494:54:44, 178.53s/it]

20/10000 round completed......................... Accurecy: 0.7673121254034118


  0%|          | 21/10000 [42:29<507:23:28, 183.05s/it]

21/10000 round completed......................... Accurecy: 0.7701705855232827


  0%|          | 22/10000 [45:45<518:29:55, 187.07s/it]

22/10000 round completed......................... Accurecy: 0.7716459197786999


  0%|          | 23/10000 [49:04<528:20:57, 190.64s/it]

23/10000 round completed......................... Accurecy: 0.7697556477639466


  0%|          | 24/10000 [52:25<536:45:57, 193.70s/it]

24/10000 round completed......................... Accurecy: 0.7712309820193638


  0%|          | 25/10000 [55:48<544:36:39, 196.55s/it]

25/10000 round completed......................... Accurecy: 0.7721530659289996


  0%|          | 26/10000 [59:13<551:33:25, 199.08s/it]

26/10000 round completed......................... Accurecy: 0.7719225449515906


  0%|          | 27/10000 [1:02:38<556:36:23, 200.92s/it]

27/10000 round completed......................... Accurecy: 0.7732134624250807


  0%|          | 28/10000 [1:06:05<561:11:56, 202.60s/it]

28/10000 round completed......................... Accurecy: 0.7738589211618258


  0%|          | 29/10000 [1:09:32<564:40:11, 203.87s/it]

29/10000 round completed......................... Accurecy: 0.7725680036883357


  0%|          | 30/10000 [1:13:00<568:31:20, 205.28s/it]

30/10000 round completed......................... Accurecy: 0.773582295988935


  0%|          | 31/10000 [1:16:29<571:37:41, 206.43s/it]

31/10000 round completed......................... Accurecy: 0.7739050253573075


  0%|          | 32/10000 [1:19:58<573:33:12, 207.14s/it]

32/10000 round completed......................... Accurecy: 0.7748732134624251


  0%|          | 33/10000 [1:23:28<575:26:01, 207.84s/it]

33/10000 round completed......................... Accurecy: 0.7747810050714615


  0%|          | 34/10000 [1:26:58<577:03:59, 208.45s/it]

34/10000 round completed......................... Accurecy: 0.7745043798985708


  0%|          | 35/10000 [1:30:27<577:35:14, 208.66s/it]

35/10000 round completed......................... Accurecy: 0.7737667127708622


  0%|          | 36/10000 [1:33:57<578:38:16, 209.06s/it]

36/10000 round completed......................... Accurecy: 0.7743199631166436


  0%|          | 37/10000 [1:37:26<578:57:11, 209.20s/it]

37/10000 round completed......................... Accurecy: 0.773582295988935


  0%|          | 38/10000 [1:40:57<580:08:17, 209.65s/it]

38/10000 round completed......................... Accurecy: 0.77293683725219


  0%|          | 39/10000 [1:44:28<581:01:08, 209.99s/it]

39/10000 round completed......................... Accurecy: 0.7737206085753804


  0%|          | 40/10000 [1:47:58<581:31:02, 210.19s/it]

40/10000 round completed......................... Accurecy: 0.7728446288612264


  0%|          | 41/10000 [1:51:30<582:22:02, 210.52s/it]

41/10000 round completed......................... Accurecy: 0.7739050253573075


  0%|          | 42/10000 [1:55:00<582:37:50, 210.63s/it]

42/10000 round completed......................... Accurecy: 0.7739050253573075


  0%|          | 43/10000 [1:58:33<583:57:33, 211.13s/it]

43/10000 round completed......................... Accurecy: 0.772706316274781


  0%|          | 44/10000 [2:02:03<583:28:53, 210.98s/it]

44/10000 round completed......................... Accurecy: 0.7718764407561088


  0%|          | 45/10000 [2:05:35<583:43:07, 211.09s/it]

45/10000 round completed......................... Accurecy: 0.7722452743199631


  0%|          | 46/10000 [2:09:06<583:26:56, 211.01s/it]

46/10000 round completed......................... Accurecy: 0.772060857538036


  0%|          | 47/10000 [2:12:37<583:51:30, 211.18s/it]

47/10000 round completed......................... Accurecy: 0.7721530659289996


  0%|          | 48/10000 [2:16:09<584:33:49, 211.46s/it]

48/10000 round completed......................... Accurecy: 0.7713692946058092


  0%|          | 49/10000 [2:19:42<585:45:32, 211.91s/it]

49/10000 round completed......................... Accurecy: 0.7721069617335178


  0%|          | 50/10000 [2:23:16<587:05:55, 212.42s/it]

50/10000 round completed......................... Accurecy: 0.7719686491470724


  1%|          | 51/10000 [2:26:48<586:29:45, 212.22s/it]

51/10000 round completed......................... Accurecy: 0.7715998155832181


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_estimator = RandomForestClassifier(n_estimators=best_estimator,random_state=0)
rf_estimator.fit(X_train, y_train)
y_pred=rf_estimator.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

save_model(rf_estimator,"Best_est_"+str(rf_estimator))
#files.download("max_depth_"+str(rf_estimator))

[[ 69 131  10  73 101]
 [  6 302  32  30  14]
 [  0 118 262   2   2]
 [ 18 121   6 223  16]
 [ 32  24   5  14 309]]
              precision    recall  f1-score   support

           0       0.55      0.18      0.27       384
           1       0.43      0.79      0.56       384
           2       0.83      0.68      0.75       384
           3       0.65      0.58      0.61       384
           4       0.70      0.80      0.75       384

    accuracy                           0.61      1920
   macro avg       0.63      0.61      0.59      1920
weighted avg       0.63      0.61      0.59      1920

Accurecy:  0.6067708333333334


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_depth = RandomForestClassifier(max_depth=best_depth,random_state=0)
rf_depth.fit(X_train, y_train)
y_pred=rf_depth.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

save_model(rf_depth,"max_depth_"+str(rf_depth))
#files.download("max_depth_"+str(rf_depth)) 

[[ 75 134   7  75  93]
 [ 13 291  36  33  11]
 [  0 117 261   4   2]
 [ 21 114   5 231  13]
 [ 35  23   4  15 307]]
              precision    recall  f1-score   support

           0       0.52      0.20      0.28       384
           1       0.43      0.76      0.55       384
           2       0.83      0.68      0.75       384
           3       0.65      0.60      0.62       384
           4       0.72      0.80      0.76       384

    accuracy                           0.61      1920
   macro avg       0.63      0.61      0.59      1920
weighted avg       0.63      0.61      0.59      1920

Accurecy:  0.6067708333333334


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_all = RandomForestClassifier(n_estimators=450,max_depth=39,random_state=0)
rf_all.fit(X_train, y_train)
y_pred=rf_all.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

save_model(rf_all,"All_"+str(rf_all))
#files.download("max_depth_"+str(rf_all))

[[ 63 134  10  74 103]
 [  8 300  30  33  13]
 [  0 120 260   2   2]
 [ 18 128   6 218  14]
 [ 33  23   4  14 310]]
              precision    recall  f1-score   support

           0       0.52      0.16      0.25       384
           1       0.43      0.78      0.55       384
           2       0.84      0.68      0.75       384
           3       0.64      0.57      0.60       384
           4       0.70      0.81      0.75       384

    accuracy                           0.60      1920
   macro avg       0.62      0.60      0.58      1920
weighted avg       0.62      0.60      0.58      1920

Accurecy:  0.5994791666666667
