#Libraries

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import pandas as pd
import matplotlib.pyplot as plt
data = 'https://raw.githubusercontent.com/RafsanJany-44/Machine-School/main/datasets/HMC_WITH_BIOM.csv'
#data="https://raw.githubusercontent.com/RafsanJany-44/Research-NREM-REM/main/dataset/REM_NREM.csv"
dataset = pd.read_csv(data)


#Spliting

In [2]:
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 0)


$Models with out KFCV

**Logistic Regression,SVM,Random Forest**

In [6]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
print("Logistic Reg Accuracy: ",lr.score(X_test, y_test))


svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
print("SVM Accuracy: ",svm.score(X_test, y_test))

rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
print("Random Forest: ",rf.score(X_test, y_test)1)


Logistic Reg Accuracy:  0.33447149643705465
SVM Accuracy:  0.7357482185273159
Random Forest:  0.7906769596199525


<h2 style='color:purple'>KFold cross validation</h2>

**Basic example**

In [12]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [13]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


<h2 style='color:purple'>cross_val_score function</h2>

In [7]:
from sklearn.model_selection import cross_val_score

**Logistic regression, SVM, Random forest using cross val score**

In [ ]:
print("Logistic regression Accurecy for 3 fold:",cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X, y,cv=3))
print("Random Forest Performance Accurecy for 3 fold:",cross_val_score(RandomForestClassifier(n_estimators=40),X, y,cv=3))
print("SVM Accurecy for 3 fold:",cross_val_score(SVC(gamma='auto'), X, y,cv=3))


Logistic regression Accurecy for 3 fold: [0.33788948 0.23768925 0.33779215]
Random Forest Performance Accurecy for 3 fold: [0.59420929 0.5072762  0.59782449]
SVM Accurecy for 3 fold: [0.36140506 0.32617963 0.40438042]


cross_val_score uses stratifield kfold by default

<h2 style='color:purple'>Parameter tunning using k fold cross validation</h2>

In [ ]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8793698637138034

In [ ]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9358915527370766

In [ ]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9494121957589801

In [ ]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9482877777434258

Here we used cross_val_score to
fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result. 