In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# New Section

In [ ]:
import numpy as np
import pandas as pd
dataset=pd.read_csv("/content/drive/MyDrive/SNU Research/Tinnitus/Tinnitus_ALR_features_106_2022.07.28.csv")

# New Section

In [ ]:
dataset.head(5)

Subject Type/Class Test Type Gap duration  n0_gap_peak_ms  p1_gap_peak_ms  \
0            Healthy      Test         20ms             101             147   
1            Healthy      Test         20ms             132             155   
2            Healthy      Test         20ms             107             160   
3            Healthy      Test         20ms              77             200   
4            Healthy      Test         20ms             153             128   

   n1_gap_peak_ms  p2_gap_peak_ms  n2_gap_peak_ms  p3_gap_peak_ms  \
0             214             263             366             105   
1             217             301             383             131   
2             221             305             396             128   
3             233             268             379             166   
4             224             264             337             147   

   n0_nogap_peak_ms  ...  Unnamed: 126  Unnamed: 127  Unnamed: 128  \
0               149  ...           NaN           NaN           NaN   
1               175  ...           NaN           NaN           NaN   
2               192  ...           NaN           NaN           NaN   
3               120  ...           NaN           NaN           NaN   
4               176  ...           NaN           NaN           NaN   

   Unnamed: 129  Unnamed: 130  Unnamed: 131  Unnamed: 132  Unnamed: 133  \
0           NaN           NaN           NaN           NaN           NaN   
1           NaN           NaN           NaN           NaN           NaN   
2           NaN           NaN           NaN           NaN           NaN   
3           NaN           NaN           NaN           NaN           NaN   
4           NaN           NaN           NaN           NaN           NaN   

   Unnamed: 134  Unnamed: 135  
0           NaN           NaN  
1           NaN           NaN  
2           NaN           NaN  
3           NaN           NaN  
4           NaN           NaN  

[5 rows x 136 columns]

In [ ]:
dataset.iloc[:, 0].value_counts()

Healthy     172
Tinnitus    158
Name: Subject Type/Class, dtype: int64

In [ ]:
X = dataset.iloc[:, 3:]
y = dataset.iloc[:, 0]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
 
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/extmath.py:985: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.7/dist-packages/sklearn/utils/extmath.py:990: RuntimeWarning: invalid value encountered in true_divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.7/dist-packages/sklearn/utils/extmath.py:1020: RuntimeWarning: invalid value encountered in true_divide
  new_unnormalized_variance -= correction ** 2 / new_sample_count


#GradientBoosting Classifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import RepeatedStratifiedKFold

classifier = GradientBoostingClassifier(n_estimators=4,random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[31  8]
 [ 4 23]]
              precision    recall  f1-score   support

     Healthy       0.89      0.79      0.84        39
    Tinnitus       0.74      0.85      0.79        27

    accuracy                           0.82        66
   macro avg       0.81      0.82      0.82        66
weighted avg       0.83      0.82      0.82        66

Accurecy:  0.8181818181818182


#Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=18,max_depth=4,random_state=0)
classifier.fit(X_train, y_train)
y_pred=classifier.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[32  7]
 [ 7 20]]
              precision    recall  f1-score   support

     Healthy       0.82      0.82      0.82        39
    Tinnitus       0.74      0.74      0.74        27

    accuracy                           0.79        66
   macro avg       0.78      0.78      0.78        66
weighted avg       0.79      0.79      0.79        66

Accurecy:  0.7878787878787878


#Ada Boost Classifier

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

classifier = AdaBoostClassifier(n_estimators=54,random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[35  4]
 [ 9 18]]
              precision    recall  f1-score   support

     Healthy       0.80      0.90      0.84        39
    Tinnitus       0.82      0.67      0.73        27

    accuracy                           0.80        66
   macro avg       0.81      0.78      0.79        66
weighted avg       0.80      0.80      0.80        66

Accurecy:  0.803030303030303


#XG

In [ ]:


import xgboost as xgb
xgb_classifier = xgb.XGBClassifier(max_depth=3,random_state=0)
xgb_classifier.fit(X_train,y_train)
y_pred = xgb_classifier.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[32  7]
 [ 9 18]]
              precision    recall  f1-score   support

     Healthy       0.78      0.82      0.80        39
    Tinnitus       0.72      0.67      0.69        27

    accuracy                           0.76        66
   macro avg       0.75      0.74      0.75        66
weighted avg       0.76      0.76      0.76        66

Accurecy:  0.7575757575757576


#KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
KNN_class = KNeighborsClassifier(n_neighbors=164)
KNN_class.fit(X_train, y_train)
y_pred=KNN_class.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[39  0]
 [19  8]]
              precision    recall  f1-score   support

     Healthy       0.67      1.00      0.80        39
    Tinnitus       1.00      0.30      0.46        27

    accuracy                           0.71        66
   macro avg       0.84      0.65      0.63        66
weighted avg       0.81      0.71      0.66        66

Accurecy:  0.7121212121212122


#With Synthetic Data

**GradientBoosting**

NON RANDOM

In [ ]:

from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import GradientBoostingClassifier


X, y = make_classification(random_state=0)

model_5 = GradientBoostingClassifier(n_estimators=9,max_depth=3,random_state=0)

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=0)

n_scores = cross_val_score(model_5, X, y, scoring='accuracy', cv=cv)

print('Mean Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Mean Accuracy: 0.883 (0.097)


Random

In [ ]:

from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import GradientBoostingClassifier

X, y = make_classification(random_state=1)

model_5 = GradientBoostingClassifier(n_estimators=9,max_depth=3,random_state=0)

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=0)

n_scores = cross_val_score(model_5, X, y, scoring='accuracy', cv=cv)

print('Mean Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Mean Accuracy: 0.953 (0.050)


#USING SMOTE

In [ ]:
X = dataset.iloc[:, 3:]
y = dataset.iloc[:, 0]


from sklearn.model_selection import train_test_split
  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
  

In [ ]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 2)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train.ravel())

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import RepeatedStratifiedKFold

classifier = GradientBoostingClassifier(n_estimators=4,random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[31  8]
 [ 4 23]]
              precision    recall  f1-score   support

     Healthy       0.89      0.79      0.84        39
    Tinnitus       0.74      0.85      0.79        27

    accuracy                           0.82        66
   macro avg       0.81      0.82      0.82        66
weighted avg       0.83      0.82      0.82        66

Accurecy:  0.8181818181818182


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=18,max_depth=4,random_state=0)
classifier.fit(X_train, y_train)
y_pred=classifier.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[31  8]
 [ 7 20]]
              precision    recall  f1-score   support

     Healthy       0.82      0.79      0.81        39
    Tinnitus       0.71      0.74      0.73        27

    accuracy                           0.77        66
   macro avg       0.77      0.77      0.77        66
weighted avg       0.77      0.77      0.77        66

Accurecy:  0.7727272727272727


In [ ]:
from sklearn.ensemble import AdaBoostClassifier

classifier = AdaBoostClassifier(n_estimators=54,random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[35  4]
 [ 9 18]]
              precision    recall  f1-score   support

     Healthy       0.80      0.90      0.84        39
    Tinnitus       0.82      0.67      0.73        27

    accuracy                           0.80        66
   macro avg       0.81      0.78      0.79        66
weighted avg       0.80      0.80      0.80        66

Accurecy:  0.803030303030303
