In [118]:
import pandas as pd
import numpy as np

In [119]:
data = 'https://raw.githubusercontent.com/RafsanJany-44/Research-NREM-REM/main/dataset/REM_NREM_O2.csv'

dataset = pd.read_csv(data)

In [120]:
dataset.head()

Sleep_Stage  MeanP_Alpha_O2  MedianF_Alpha_O2  MeanF_Alpha_O2  \
0        NREM         0.00023          10.61463        18.48195   
1        NREM         0.00023          10.36488        18.10732   
2        NREM         0.00025           9.74049        17.35805   
3        NREM         0.00027           9.49073        17.60780   
4        NREM         0.00036           9.24098        16.48390   

   Spectral Edge_Alpha_O2  PeakF_Alpha_O2  MeanP_Beta_O2  MedianF_Beta_O2  \
0                17.98244        10.73951        0.00034         18.23220   
1                17.48293        10.24000        0.00032         18.10732   
2                16.73366         9.86537        0.00031         17.23317   
3                16.85854         8.11707        0.00033         17.73268   
4                15.98439         8.11707        0.00039         15.98439   

   MeanF_Beta_O2  Spectral Edge_Beta_O2  ...  MeanP_Delta_O2  \
0       25.84976               28.47220  ...         0.00112   
1       26.22439               28.72195  ...         0.00070   
2       26.47415               28.84683  ...         0.00077   
3       26.47415               28.59707  ...         0.00130   
4       24.47610               25.97463  ...         0.00123   

   MedianF_Delta_O2  MeanF_Delta_O2  Spectral Edge_Delta_O2  PeakF_Delta_O2  \
0           0.74927         6.36878                 2.87220         0.62439   
1           0.99902         6.86829                 3.62146         0.74927   
2           1.49854         6.49366                 4.12098         0.74927   
3           1.87317         6.11902                 3.74634         0.37463   
4           1.49854         6.61854                 3.74634         0.74927   

   MeanP_Gamma_O2  MedianF_Gamma_O2  MeanF_Gamma_O2  Spectral Edge_Gamma_O2  \
0        0.000076          32.71805        43.83220                49.95122   
1        0.000072          32.09366        44.33171                49.95122   
2        0.000069          33.09268        43.95707                49.95122   
3        0.000070          31.59415        42.83317                49.95122   
4        0.000060          29.47122        45.08098                49.95122   

   PeakF_Gamma_O2  
0        49.95122  
1        49.95122  
2        49.95122  
3        49.95122  
4        49.95122  

[5 rows x 26 columns]

In [121]:
X = dataset.iloc[:, 1:76].values
y = dataset.iloc[:, 0].values

In [122]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 0)

In [123]:
X_train.shape, X_test.shape

((59694, 25), (29402, 25))

In [124]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train =sc.fit_transform(X_train)

X_test =sc.fit_transform(X_test)

In [125]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=20, random_state=0)
classifier.fit(X_train, y_train)
y_pred=classifier.predict(X_test)

In [152]:
from re import match
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,multilabel_confusion_matrix,ConfusionMatrixDisplay

def multi_accurecy(mat):
  acu=[]
  for i in mat:
    tp=i[0][0]
    fp=i[0][1]
    fn=i[1][0]
    tn=i[1][1]
    a=(tp+tn)/(tp+fn+tn+fn)
    acu.append(a)
  return acu


print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred,normalize=False))

print(multilabel_confusion_matrix(y_test,y_pred))
cm=multilabel_confusion_matrix(y_test,y_pred,labels=clf.classes_)
mat=multilabel_confusion_matrix(y_test,y_pred)

acureccy=multi_accurecy(mat)

print("Accurecy for NREM: ",acureccy[0])
print("Accurecy for REM: ",acureccy[1])

disp = ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=clf.classes_)
disp.plot()
plt.show()


[[23621   309]
 [ 4565   907]]
              precision    recall  f1-score   support

        NREM       0.84      0.99      0.91     23930
         REM       0.75      0.17      0.27      5472

    accuracy                           0.83     29402
   macro avg       0.79      0.58      0.59     29402
weighted avg       0.82      0.83      0.79     29402

Accurecy:  24528
[[[  907  4565]
  [  309 23621]]

 [[23621   309]
  [ 4565   907]]]


AttributeError: ignored

In [148]:

acu=[]
for i in mat:
  tp=i[0][0]
  fp=i[0][1]
  fn=i[1][0]
  tn=i[1][1]
  a=(tp)/(tp+fp)
  print(a)
  acu.append(a)



0.16575292397660818
0.987087338069369
