###Function

In [ ]:
!pip install imbalanced-learn
!pip install ipywidgets


     ------------------------------------ 137.8/137.8 kB 326.1 kB/s eta 0:00:00
     ---------------------------------------- 2.0/2.0 MB 2.5 MB/s eta 0:00:00
     ------------------------------------- 384.3/384.3 kB 12.1 MB/s eta 0:00:00


In [1]:
from imblearn.over_sampling import SMOTE
import ipywidgets as widgets
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd

In [ ]:
def ddataset_balance(X_temp, y_temp):
  smote = SMOTE()
  X_temp, y_temp= smote.fit_resample(X_temp, y_temp)
  return pd.concat([pd.DataFrame(X_temp), pd.DataFrame(y_temp)], axis=1)

def Xy_balance(X_temp, y_temp):
  smote = SMOTE()
  return smote.fit_resample(X_temp, y_temp)

def Search_Null(dataset):
  dic={}
  for col in list(dataset.columns):
    rows = []
    flage = 0
    for row in range(dataset.shape[0]):
      if str(dataset[col][row]) == "nan":
        rows.append(row)
        flage = 1
    if flage ==1:
      dic[col] = rows
  
  return dic


def models_check_box(models):
  from IPython.display import display
  new_keys=[]
  for i in models:
    i=widgets.Checkbox(
      value=False,
      description=str(i),
      disabled=False,
      indent=False
      )
    display(i)
    new_keys.append(i)
  return new_keys


def StandardScaleData(data):
  scaler = StandardScaler()
  scaler.fit(data)
  return  scaler.transform(data)


def MinMaxScaleData(data):
  scaler = MinMaxScaler()
  scaler.fit(data)
  return scaler.transform(data)

#Starting

In [8]:
df = pd.read_csv("https://raw.githubusercontent.com/RafsanJany-44/Reopen_5_stage_sleep_classifiacation/main/EEG_HMC_FeatureExtraction_2023.01.19.csv")
print(df.shape)
df.dropna(axis = 0,how='any', inplace = True)
df.to_csv("New_EEG_NullValueRemoved_HMC.csv")
dataset = pd.read_csv("New_EEG_NullValueRemoved_HMC.csv")
dataset.drop(dataset.columns[dataset.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
target = "Sleep Stage"
result = {}
print(dataset.shape)

(108920, 52)
(108450, 52)


###Enocoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
dataset[target]=encoder.fit_transform(dataset[target])

###Spliting into X and y

In [ ]:
X =  dataset.loc[:,dataset.columns != target]  # removing Sleep Stage
X =  X.loc[:,X.columns != "Subject"]            # removing Status
X =  X.loc[:,X.columns != "Epoch"]             # removing Epoch
y = dataset[target]

X.head(10)

MeanP_Alpha_F4  MeanP_Beta_F4  MeanP_Theta_F4  MeanP_Delta_F4  \
0         0.00051        0.00071         0.00121         0.01070   
1         0.00040        0.00051         0.00062         0.00539   
2         0.00036        0.00047         0.00059         0.00967   
3         0.00035        0.00047         0.00043         0.00228   
4         0.00033        0.00043         0.00053         0.00436   
5         0.00036        0.00043         0.00038         0.00194   
6         0.00034        0.00047         0.00041         0.00159   
7         0.00035        0.00048         0.00040         0.00128   
8         0.00035        0.00042         0.00052         0.00134   
9         0.00050        0.00053         0.00077         0.00290   

   MeanP_Gamma_F4  MeanP_Alpha_C4  MeanP_Beta_C4  MeanP_Theta_C4  \
0        0.000240         0.00041        0.00067         0.00061   
1        0.000120         0.00038        0.00052         0.00046   
2        0.000100         0.00036        0.00049         0.00044   
3        0.000110         0.00036        0.00053         0.00040   
4        0.000094         0.00031        0.00043         0.00038   
5        0.000085         0.00039        0.00048         0.00041   
6        0.000100         0.00038        0.00054         0.00048   
7        0.000094         0.00041        0.00064         0.00051   
8        0.000094         0.00043        0.00047         0.00078   
9        0.000087         0.00067        0.00073         0.00139   

   MeanP_Delta_C4  MeanP_Gamma_C4  ...  DAR_C4  DAR_O2  DAR_G  DTR_F4  DTR_O2  \
0         0.00353        0.000210  ...    8.61   25.00  18.20    8.85   18.60   
1         0.00238        0.000100  ...    6.26   30.10  16.60    8.69   28.90   
2         0.00312        0.000087  ...    8.67   10.50  15.30   16.40    9.58   
3         0.00144        0.000110  ...    4.00    3.64   4.72    5.30    3.64   
4         0.00149        0.000081  ...    4.81    7.61   8.54    8.23    7.29   
5         0.00100        0.000081  ...    2.56    2.44   3.47    5.11    2.64   
6         0.00138        0.000100  ...    3.63    4.87   4.39    3.88    4.48   
7         0.00134        0.000110  ...    3.27    3.04   3.32    3.20    2.59   
8         0.00156        0.000087  ...    3.63    3.08   3.51    2.58    2.14   
9         0.00549        0.000095  ...    8.19    4.81   6.27    3.77    2.77   

   DTABR_F4  DTABR_C4  DTABR_O2  DTABR_G      P_G  
0      9.77      3.83      8.67     7.42  0.00918  
1      6.60      3.16     12.30     7.34  0.00636  
2     12.40      4.19      4.62     7.06  0.00628  
3      3.30      2.07      1.90     2.42  0.00278  
4      6.43      2.53      3.49     4.15  0.00369  
5      2.94      1.62      1.52     2.02  0.00238  
6      2.47      2.02      2.40     2.30  0.00260  
7      2.02      1.76      1.76     1.85  0.00240  
8      2.42      2.60      2.02     2.34  0.00260  
9      3.56      4.91      2.95     3.81  0.00520  

[10 rows x 49 columns]

###USing SMOTE for balancing

In [ ]:
new_dataset =  balance(X,y)

In [ ]:
new_dataset[target].value_counts()

4    39428
0    39428
1    39428
2    39428
3    39428
Name: Sleep Stage, dtype: int64

#Feature Selection

In [ ]:
number_of_feat = 30

###ANOVA with f classifciation

In [ ]:
from sklearn.datasets import make_classification
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
import pandas as pd



fs = SelectKBest(score_func=f_classif, k=5)
fit = fs.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)

featureScores = pd.concat([dfcolumns,dfscores],axis=1)

featureScores.columns = ['Best_columns','Score_ANOVA'] 

lyst = featureScores.nlargest(number_of_feat,'Score_ANOVA')

#lyst.to_csv('Filter_Method_ANOVA_with_f_classif.csv')

list_of_feat = list(lyst["Best_columns"])

###Embedded Method

In [ ]:
''''
from sklearn.linear_model import LassoCV
reg = LassoCV()
reg.fit(X, y)
print("Best alpha using built-in LassoCV: %f" % reg.alpha_)
print("Best score using built-in LassoCV: %f" %reg.score(X,y))
coef = pd.Series(reg.coef_, index = X.columns)

print("Lasso picked " + str(sum(coef != 0)) + " variables and eliminated the other " +  str(sum(coef == 0)) + " variables")

imp_coef = coef.sort_values()

list_of_feat=[]


for i in range(coef.shape[0]):
  if coef[i]!=0:
    list_of_feat.append(dataset.iloc[:0,i+3].name)
    
df = pd.DataFrame(list_of_feat, columns=['Best_Features'])

#df.to_csv("Embedded_Method.csv")

list_of_feat = list(df["Best_Features"])
if number_of_feat < len(list_of_feat):
  list_of_feat = list_of_feat[:number_of_feat]
'''

###Pearson's with f regression

In [ ]:
'''
from sklearn.datasets import make_regression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
import pandas as pd


fs = SelectKBest(score_func=f_regression, k=5)
fit = fs.fit(X,y)

dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(dataset.columns)
featureScores = pd.concat([dfcolumns,dfscores],axis=1)

featureScores.columns = ['Best_columns','Score_pearsons'] 


lyst = featureScores.nlargest(number_of_feat,'Score_pearsons')

#lyst.to_csv('Filter_Method_Pearson’s_with_f_regression.csv')

list_of_feat = list(lyst["Best_columns"])
'''

###Sequential Feature Selection

In [ ]:
''''
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
sfs = SequentialFeatureSelector(knn, n_features_to_select=number_of_feat)
sfs.fit(X, y)
list_of_feat=[]
list_of_feat=list(sfs.get_feature_names_out(X.columns))

df = pd.DataFrame(list_of_feat, columns=['Best_Features'])

#df.to_csv("Filter_Method_Sequential_feat_Selection_KNN.csv")

list_of_feat = list(df["Best_Features"])
if number_of_feat < len(list_of_feat):
  list_of_feat = list_of_feat[:number_of_feat]
  '''

###Feature list

In [ ]:
dfcolumns = pd.DataFrame(list_of_feat)
print(dfcolumns)

#Data Spliting Into X,y

In [ ]:
#X_new = new_dataset[list_of_feat]
#y_new = new_dataset[target]

#X_new =  new_dataset.loc[:,new_dataset.columns != target] 
#y_new = new_dataset[target]

X_new = X
y_new = y

#X_new.head(10)
print(X_new.shape)

(108450, 49)


#Data Scaling

In [ ]:
X_new =  StandardScaleData(X_new)
print(X_new.shape)
X_new

(108450, 49)


array([[-0.0653349 , -0.06741043, -0.04805037, ..., -0.11649183,
        -0.11649183, -0.12025476],
       [-0.07426116, -0.09237015, -0.06824147, ..., -0.11649183,
        -0.11649183, -0.13409893],
       [-0.07750708, -0.0973621 , -0.06926814, ..., -0.11649183,
        -0.11649183, -0.13449167],
       ...,
       [-0.07426116, -0.10984196, -0.07269036, ..., -0.11649183,
        -0.11649183, -0.15363786],
       [-0.0653349 , -0.06241848, -0.06892592, ..., -0.11649183,
        -0.11649183, -0.13620992],
       [-0.00285108,  0.22337036, -0.02272594, ..., -0.11649183,
        -0.11649183, -0.03915347]])

#Data Spliting Into Train and Testing

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_new, y_new, test_size = 0.2, random_state = 0)

###Only Training Balancing

In [ ]:
X_train,y_train = Xy_balance(X_train,y_train)




---



# **Training**



---



##ADABOOST

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

ada_defult = AdaBoostClassifier(random_state=0)
ada_defult.fit(X_train, y_train)
y_pred = ada_defult.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))
result[(ada_defult,1,'AdaBoostClassifier')]=accuracy_score(y_test, y_pred)


[[ 554  312  147  627  745]
 [ 731 2478 2521 1493  647]
 [  46  397 3580  135   61]
 [ 553  403  271 1925  248]
 [ 414  168   76  202 2956]]
              precision    recall  f1-score   support

           0       0.24      0.23      0.24      2385
           1       0.66      0.31      0.43      7870
           2       0.54      0.85      0.66      4219
           3       0.44      0.57      0.49      3400
           4       0.63      0.77      0.70      3816

    accuracy                           0.53     21690
   macro avg       0.50      0.55      0.50     21690
weighted avg       0.55      0.53      0.51     21690

Accurecy:  0.5298755186721992




---



---



##Graddient Boosting

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import RepeatedStratifiedKFold

gradBoost_default = GradientBoostingClassifier(random_state=0)
gradBoost_default.fit(X_train, y_train)
y_pred = gradBoost_default.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))
result[(gradBoost_default,2,'GradientBoostingClassifier')]=accuracy_score(y_test, y_pred)

[[109  20  28   6]
 [ 22 111   6   6]
 [ 26  17 110  15]
 [ 10  11  18 120]]
              precision    recall  f1-score   support

           0       0.65      0.67      0.66       163
           1       0.70      0.77      0.73       145
           2       0.68      0.65      0.67       168
           3       0.82      0.75      0.78       159

    accuracy                           0.71       635
   macro avg       0.71      0.71      0.71       635
weighted avg       0.71      0.71      0.71       635

Accurecy:  0.7086614173228346




---



---



##Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_default = RandomForestClassifier(random_state=0)
rf_default.fit(X_train, y_train)
y_pred=rf_default.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))
result[(rf_default,3,'RandomForestClassifier')]=accuracy_score(y_test, y_pred)

[[120  17  18   8]
 [ 21 117   5   2]
 [ 24   9 125  10]
 [  6   4   9 140]]
              precision    recall  f1-score   support

           0       0.70      0.74      0.72       163
           1       0.80      0.81      0.80       145
           2       0.80      0.74      0.77       168
           3       0.88      0.88      0.88       159

    accuracy                           0.79       635
   macro avg       0.79      0.79      0.79       635
weighted avg       0.79      0.79      0.79       635

Accurecy:  0.7905511811023622




---



---



##XGB

In [ ]:
import xgboost as xgb
xgb_deafult = xgb.XGBClassifier(random_state=0)
xgb_deafult.fit(X_train.values,y_train.values)
y_pred = xgb_deafult.predict(X_test.values)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))
result[(xgb_deafult,4,'xgboost')]=accuracy_score(y_test, y_pred)

[[113  20  21   9]
 [ 26 104   9   6]
 [ 32  20  99  17]
 [ 10   5  24 120]]
              precision    recall  f1-score   support

           0       0.62      0.69      0.66       163
           1       0.70      0.72      0.71       145
           2       0.65      0.59      0.62       168
           3       0.79      0.75      0.77       159

    accuracy                           0.69       635
   macro avg       0.69      0.69      0.69       635
weighted avg       0.69      0.69      0.69       635

Accurecy:  0.6866141732283465


##KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_default = KNeighborsClassifier()
knn_default.fit(X_train, y_train)
y_pred=knn_default.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))
result[(knn_default,5,'KNeighborsClassifier')]=accuracy_score(y_test, y_pred)

[[ 90  34  17  22]
 [ 22 110   3  10]
 [ 29  20 104  15]
 [ 15   7  25 112]]
              precision    recall  f1-score   support

           0       0.58      0.55      0.56       163
           1       0.64      0.76      0.70       145
           2       0.70      0.62      0.66       168
           3       0.70      0.70      0.70       159

    accuracy                           0.66       635
   macro avg       0.66      0.66      0.66       635
weighted avg       0.66      0.66      0.65       635

Accurecy:  0.6551181102362205


##NB

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb_deafult = GaussianNB()
nb_deafult.fit(X_train, y_train)
y_pred = nb_deafult.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))
result[(nb_deafult,6,'GaussianNB')]=accuracy_score(y_test, y_pred)

[[80 22 23 38]
 [43 53 26 23]
 [22 40 85 21]
 [19 13 46 81]]
              precision    recall  f1-score   support

           0       0.49      0.49      0.49       163
           1       0.41      0.37      0.39       145
           2       0.47      0.51      0.49       168
           3       0.50      0.51      0.50       159

    accuracy                           0.47       635
   macro avg       0.47      0.47      0.47       635
weighted avg       0.47      0.47      0.47       635

Accurecy:  0.47086614173228347




---



---



#Result

In [ ]:

models=[]

for i in result:
  models.append(i[0])
  print(i[0],i[1]," : ",result[i])
  print("---------------------------------------------------------------")
  print()
